export const countries = [
  { code: "United_States", name: "United States" },
  { code: "Canada", name: "Canada" },
  { code: "United_Kingdom", name: "United Kingdom" },
  { code: "Australia", name: "Australia" },
  { code: "Germany", name: "Germany" },
  { code: "France", name: "France" },
  { code: "Italy", name: "Italy" },
  { code: "Spain", name: "Spain" },
  { code: "Japan", name: "Japan" },
  { code: "China", name: "China" },
  { code: "India", name: "India" },
  { code: "Brazil", name: "Brazil" },
  { code: "Mexico", name: "Mexico" },
  { code: "Russia", name: "Russia" },
  { code: "South_Africa", name: "South Africa" },
  { code: "South_Korea", name: "South Korea" },
  { code: "Singapore", name: "Singapore" },
  { code: "Sweden", name: "Sweden" },
  { code: "Norway", name: "Norway" },
  { code: "Denmark", name: "Denmark" },
  { code: "Netherlands", name: "Netherlands" },
  { code: "Belgium", name: "Belgium" },
  { code: "Switzerland", name: "Switzerland" },
  { code: "Austria", name: "Austria" },
  { code: "New_Zealand", name: "New Zealand" },
];